<a href="https://colab.research.google.com/github/muhamadrefo/Kolera/blob/master/Logistic%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
%cd /content/drive/My Drive/Dataset/Kolera

/content/drive/My Drive/Dataset/Kolera


In [3]:
%ls

datasets_kolera.csv


In [39]:
import pandas as pd
import csv

data = pd.read_csv('Kolera (2).csv')
data

Country  ...             WHO Region
0            Afghanistan  ...  Eastern Mediterranean
1            Afghanistan  ...  Eastern Mediterranean
2            Afghanistan  ...  Eastern Mediterranean
3            Afghanistan  ...  Eastern Mediterranean
4            Afghanistan  ...  Eastern Mediterranean
...                  ...  ...                    ...
2487  Russian Federation  ...                 Europe
2488  Russian Federation  ...                 Europe
2489              Sweden  ...                 Europe
2490         Switzerland  ...                 Europe
2491            Cambodia  ...        Western Pacific

[2492 rows x 6 columns]

In [40]:
import numpy as np
import joblib
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics

In [41]:
df = data.loc[2:,:]
df

Country  ...             WHO Region
2            Afghanistan  ...  Eastern Mediterranean
3            Afghanistan  ...  Eastern Mediterranean
4            Afghanistan  ...  Eastern Mediterranean
5            Afghanistan  ...  Eastern Mediterranean
6            Afghanistan  ...  Eastern Mediterranean
...                  ...  ...                    ...
2487  Russian Federation  ...                 Europe
2488  Russian Federation  ...                 Europe
2489              Sweden  ...                 Europe
2490         Switzerland  ...                 Europe
2491            Cambodia  ...        Western Pacific

[2490 rows x 6 columns]

In [42]:
X = df.iloc[:, 2:5]
y = df.iloc[:, -1]

In [43]:
from sklearn.model_selection import train_test_split as tt
x_train, x_test, y_train, y_test = tt(X,y, test_size =0.2)

In [53]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train, y_train)
pred_lr = LR.predict(x_test)
acc_lr = (np.sum(pred_lr == y_test)/ y_test.size)*100
joblib.dump(LR, 'model_LR1.pkl')

print('Using Logistic Regression Method')
print('Accuracy - ',acc_lr)
#print('Recall - ',metrics.recall_score(y_test, pred_lr))
#print('Precision Score - ', metrics.precision_score(y_test, pred_lr))
print('Confusion Matrix \n', metrics.confusion_matrix(y_test, pred_lr))
print('\n')
print("Classification Report: \n", metrics.classification_report(y_test, pred_lr))

Using Logistic Regression Method
Accuracy -  39.959839357429715
Confusion Matrix 
 [[177  13   0   0   1   0]
 [ 41  11   0   0   0   0]
 [ 35   9   0   0   0   0]
 [ 62   0   0   0   0   0]
 [ 43  10   0   0  11   0]
 [ 68  17   0   0   0   0]]


Classification Report: 
                        precision    recall  f1-score   support

               Africa       0.42      0.93      0.57       191
             Americas       0.18      0.21      0.20        52
Eastern Mediterranean       0.00      0.00      0.00        44
               Europe       0.00      0.00      0.00        62
      South-East Asia       0.92      0.17      0.29        64
      Western Pacific       0.00      0.00      0.00        85

             accuracy                           0.40       498
            macro avg       0.25      0.22      0.18       498
         weighted avg       0.30      0.40      0.28       498



In [54]:
%ls

 datasets_kolera.csv  'Kolera (2).csv'   model_LR1.pkl
'Kolera (1).csv'       Kolera.csv
